---
# Playbook principal — Module 07
# FR : Remplacez les valeurs par défaut si nécessaire
# EN : Replace default values if needed

- name: Configurer les serveurs d'application / Configure app servers
  hosts: app_servers
  become: no   # FR: passer à 'yes' pour des serveurs réels / EN: set to 'yes' for real servers

  vars:
    app_port: 5000
    app_version: "1.0.0"
    docker_image: "votre_username/todo-api"

  roles:
    - role: todo-api
      tags: [deploy, app]
