version: '3.9'

services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: appdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-net

  php:
    build:
      context: ./php-app
    container_name: php
    volumes:
      - ./php-app:/var/www/html
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-net
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./php-app:/var/www/html
    depends_on:
      - php
    networks:
      - app-net

volumes:
  db-data:

networks:
  app-net:
    driver: bridge

