apiVersion: batch/v1
kind: Job
metadata:
  name: date-job
spec:
  template:
    spec:
      containers:
      - name: print-date
        image: busybox
        command: ["sh", "-c", "echo 'La date actuelle est :' && date && sleep 5"]
      restartPolicy: Never
  backoffLimit: 3

