apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: restricted-binding
  namespace: lab
subjects:
- kind: ServiceAccount
  name: restricted-sa
  namespace: lab
roleRef:
  kind: Role
  name: viewer
  apiGroup: rbac.authorization.k8s.io
